languageCode = "en-us"
title = "Gabriele Russo Russo"
theme = "researcher"
staticDir = "assets"
enableGitInfo = false
canonifyURLs = true

#baseURL = "https://example.com"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Gabriele Russo Russo"
  description = ""
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Lato, PT Sans, Open Sans, Helvetica"
    fontSize = "13pt"
    pageWidth = "820px"
    avatarSize = "100px"
    colorBlack = "#222222"
    colorMain = "#0b5bb5"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/grussorusso"
  [[params.socialIcons]]
    icon = "ai ai-google-scholar"
    title = "Scholar"
    url = "https://scholar.google.com/citations?user=rRiNfS0AAAAJ"
  [[params.socialIcons]]
    icon = "ai ai-dblp"
    title = "DBLP"
    url = "https://dblp.org/pid/214/1442.html"

#[permalinks]
#  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 2
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 2
  [[menu.main]]
    name = "Software"
    url = "/software"
    weight = 2
  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 2
    # 'pre' and 'post' hooks are available
	#pre = '<i class="my-fa-icon fa-regular fa-file-pdf"></i>&nbsp;'

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

