languageCode = "en-us"
title = "Gabriele Russo Russo"
theme = "researcher"
staticDir = "assets"
enableGitInfo = false
canonifyURLs = true

#baseURL = "https://example.com"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Gabriele Russo Russo"
  description = ""
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Raleway, Helvetica"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#0061cf"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/grussorusso"

#[permalinks]
#  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

